<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="order_route_tests.py" name="order_route_tests.OrderRouteTest-20200424152752" skipped="0" tests="5" time="0.013" timestamp="2020-04-24T15:27:54">
	<testcase classname="order_route_tests.OrderRouteTest" file="src\unittest\python\order_route_tests.py" line="68" name="test_get_orders" time="0.003" timestamp="2020-04-24T15:27:54">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="order_route_tests.OrderRouteTest" file="src\unittest\python\order_route_tests.py" line="80" name="test_get_orders_unauthorized" time="0.002" timestamp="2020-04-24T15:27:54">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="order_route_tests.OrderRouteTest" file="src\unittest\python\order_route_tests.py" line="54" name="test_send_order_with_invalid_address" time="0.003" timestamp="2020-04-24T15:27:54">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="order_route_tests.OrderRouteTest" file="src\unittest\python\order_route_tests.py" line="28" name="test_send_order_with_invalid_order" time="0.002" timestamp="2020-04-24T15:27:54">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="order_route_tests.OrderRouteTest" file="src\unittest\python\order_route_tests.py" line="42" name="test_send_order_with_valid_order" time="0.003" timestamp="2020-04-24T15:27:54">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
