<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="account_route_tests.py" name="account_route_tests.AccountRouteTest-20200412173944" skipped="0" tests="5" time="0.016" timestamp="2020-04-12T17:39:44">
	<testcase classname="account_route_tests.AccountRouteTest" file="src\unittest\python\account_route_tests.py" line="47" name="test_create_customer_account_but_username_is_taken" time="0.007" timestamp="2020-04-12T17:39:44">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="account_route_tests.AccountRouteTest" file="src\unittest\python\account_route_tests.py" line="58" name="test_create_customer_account_succesfully" time="0.003" timestamp="2020-04-12T17:39:44">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="account_route_tests.AccountRouteTest" file="src\unittest\python\account_route_tests.py" line="37" name="test_create_customer_account_with_invalid_account_data" time="0.002" timestamp="2020-04-12T17:39:44">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="account_route_tests.AccountRouteTest" file="src\unittest\python\account_route_tests.py" line="30" name="test_create_customer_account_with_missing_fields" time="0.001" timestamp="2020-04-12T17:39:44">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="account_route_tests.AccountRouteTest" file="src\unittest\python\account_route_tests.py" line="69" name="test_static_page" time="0.003" timestamp="2020-04-12T17:39:44">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
